# This workflow builds and deploys a Docker image to Docker Hub
# when changes are pushed to the "redash" branch.

name: Build and Deploy LLM Docker Image

# The event that triggers the workflow
on:
  push:
    branches:
      - redash

# The set of jobs (steps) to be run
jobs:
  # The job name
  build_and_deploy:
    # The runner on which the job will run
    runs-on: ubuntu-latest

    # The steps of the job
    steps:
      # Step 1: Clone the repository
      # We use a custom action to clone this repository
      # https://github.com/actions/checkout
      - name: Clone This Repository
        uses: actions/checkout@v2

      # Step 2: Initialize Docker Build
      # We use a custom action to initialize the Docker build
      - name: Init Docker Build
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub
      # We use a custom action to log in to Docker Hub
      # https://github.com/docker/login-action
      - name: Hub Login (ghcr.io)
        uses: docker/login-action@v1
        with:
          # The Docker Hub username
          username: ${{ secrets.USERNAME }}
          # The Docker Hub password
          password: ${{ secrets.PASSWORD }}

      # Step 4: Build and Deploy Docker Image
      # We use a custom action to build and push the Docker image
      # https://github.com/docker/build-push-action
      - name: Build and Deploy Docker Image
        uses: docker/build-push-action@v2
        with:
          # The Docker build context
          context: .
          # Whether to push the Docker image
          push: true
          # The tags for the Docker image
          tags: dockterj/redash-chatbot-llm:1.0.0